% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Jul-2024 11:46:33
%  MATLAB version: 24.1.0.2653294 (R2024a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('hatdog.mat');

g = saveVarsMat.g; % <500x500 uint8> too many elements

img_blue = saveVarsMat.img_blue; % <500x500x3 uint8> too many elements

img_color = saveVarsMat.img_color; % <500x500x3 uint8> too many elements

img_green = saveVarsMat.img_green; % <500x500x3 uint8> too many elements

img_red = saveVarsMat.img_red; % <500x500x3 uint8> too many elements

clear saveVarsMat;
